### ISSUE TITLE
Steam Kurulum Sonrası Driver Hatası - Pisilinux 2.0 

### ISSUE THREAD

**Issue by hsirin** [pisilinux/pisilife-2#52]
Depolar güncel. ''sudo pisi em -dvy steam'' ile kurulumunu yaptım. Çift tık ile çalışmadı. Konsoldan çalıştırmaya çalışınca bu hatayı verdi.

himmet@himmet-pc: ~ $ steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on pisilinux 2.0 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

**Comment by hsirin** [comment]
```sudo pisi em -dvy steam``` ve sonrası:

http://dpaste.com/2PGDRPE

Kurulumdan sonra ``` steam ``` komutu verince aşağıdaki hatayı veriyor:
```himmet@himmet-pc: ~ $ steam
Couldn't find dpkg, please update steamdeps for your distribution.
Running Steam on pisilinux 2.0 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
```
---- Depolar ve paketler güncel

**Comment by erkanisik1** [comment]
sudo pisi bi -dvy https://raw.githubusercontent.com/pisilinux/pisilife-2/master/steam/pspec.xml ile pisi paketini oluşturup, oluşan pisi dosyasına çift tıklayarak kurabilirsin yeni sürüme güncellendi ve sorunu giderildi.

**Comment by erkanisik1** [comment]
en sondaki hatadan anladığım kadarıyla ekran kartınız steam için yetersiz diyor. ekran kartınız nedir acaba birde sisteminiz güncelmi ve hangü sürüm pisilinux kurulu sisteminizde. benim sistemimde ati HD8370D işlemci içindeki ekran kartı var pisi 2.0 atatürk kurulu ve sistem güncel, paket yöneticisi çalışmıyor dediğinize göre sisteminizde baya bir sorun var gibi gözüküyor

**Comment by hsirin** [comment]
Sistemi yeniden kurup paketleri ve depoları güncelledikten sonra yukarıda önerdiğiniz gibi denedim. Bu sefer paket yöneticisi de çalışıyor. Bu sefer böyle bir hata verdi:

`himmet@himmet-pc: ~ $ steam`
`Couldn't find dpkg, please update steamdeps for your distribution.`
`Running Steam on pisilinux 2.0 64-bit`
`STEAM_RUNTIME is enabled automatically`
`Pins up-to-date!`
`/home/himmet/.local/share/Steam/steam.sh: satır 823: /home/himmet/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: Böyle bir dosya ya da dizin yok`
`WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.`
`himmet@himmet-pc: ~ $`
